### 두 직선의 계수를 정의합니다
#### 첫 번째 직선: 2x + 3y = 5
#### 두 번째 직선: -x + y = 5

In [2]:
import numpy as np

In [1]:
A = np.array([[2, 3], [-1, 1]])
B = np.array([5, 5])

In [2]:
np.linalg.solve(A, B)

array([-2.,  3.])

In [3]:
!pip install sympy

In [4]:
from sympy import Matrix

In [5]:
A_Matrix = np.array([[2, 3], [-1, 1]])
sympy_matrix = Matrix(A)

In [6]:
rref_matrix, pivot_columns = sympy_matrix.rref()
print("행렬의 rref")
print(rref_matrix)
print("Pivot columns", pivot_columns)

행렬의 rref
Matrix([[1, 0], [0, 1]])
Pivot columns (0, 1)


<a href="https://adamdhalla.medium.com/linear-algebra-4-reduced-row-echelon-form-for-solving-ax-0-74f64b4f37ce">RREF 참고자료</a>

### 두 직선의 계수를 정의합니다
#### 첫 번째 직선: 2x + 3y = 5
#### 두 번째 직선: -2x - 3y = 15

In [3]:
A = np.array([[2, 3], [-2, -3]])
B = np.array([5, 15])

In [5]:
sympy_matrix = Matrix(A)

In [6]:
rref_m, pivot_c = sympy_matrix.rref()
rref_m, pivot_c

(Matrix([
 [1, 3/2],
 [0,   0]]),
 (0,))

### 3개의 평면의 계수를 정의합니다
#### 첫 번째 평면: 2x + 3y + 7z = 5
#### 두 번째 평면: 3x + 4y + 12z = 7
#### 세 번째 평면: -6x + 6y + 5z = 13

In [15]:
A_x = np.array([2, 3, 7])
B_y = np.array([3, 4, 12])
C_z = np.array([-6, 6, 5])
b = np.array([5, 7, 13]) # 결과 벡터

In [26]:
# 열벡터 형태로 행렬 생성, 벡터들을 열벡터로 전치
matrix = np.array([A_x, B_y, C_z]).T

In [24]:
result = np.linalg.solve(matrix, b)
result

array([ 4.54929577, -1.53521127, -0.08450704])

In [27]:
combined_result = result[0]*A_x + result[1]*B_y + result[2]*C_z
combined_result
# 세 백터가 모두 독립이므로 해가 존재
# 해는 세 벡터의 선형결합으로 만들어짐, 세 백터의 span에 포함됨

array([ 5.,  7., 13.])

<h3>C벡터는 A와 B벡터의 선형 결합으로 이루어진 벡터이므로 평면안에 포함된다.<br />
그래서 b를 구하지 못한다.</h3>

In [34]:
A_x = np.array([2, 3, 7])
B_y = np.array([3, 4, 12])
C_z = np.array([1, 1, 5])
b = np.array([5, 7, 13])

matrix = np.array([A_x, B_y, C_z]).T
result = np.linalg.solve(matrix, b)
combined_result = result[0]*A_x + result[1]*B_y + result[2]*C_z
result, combined_result

(array([ 4.50359963e+15, -4.50359963e+15,  4.50359963e+15]),
 array([ 5.,  9., 12.]))

In [35]:
# 세 벡터 정의
A_x = np.array([2, 3, 7])
B_y = np.array([3, 4, 12])
C_z = np.array([7, 10, 26])

In [36]:
sympy_matrix_three_dim = Matrix([A_x, B_y, C_z])
sympy_matrix_three_dim

Matrix([
[2,  3,  7],
[3,  4, 12],
[7, 10, 26]])

In [38]:
rrem_f, pivot_c = sympy_matrix_three_dim.rref()
rrem_f, pivot_c

(Matrix([
 [1, 0,  8],
 [0, 1, -3],
 [0, 0,  0]]),
 (0, 1))